repos:
#   - repo: https://github.com/gruntwork-io/pre-commit
#     rev: v0.0.8
#     hooks:
#       - id: shellcheck
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: trailing-whitespace
